# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome que vai aparecer nas opções de pipe
name: 'Execução Manual'

# regras de disparo da execução (triggers/gatilhos)
# gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:

jobs:
  # um exemplo de como é a a etrutura ou a lógica da criação do job
  # build:
  #  steps:
  #    - baixar as dependências
  #    - subir a aplicação
  #    - gerar a versão
  # tests:
  #  steps:
  #    - instalar as dependências
  #    - executar o comando para rodar os testes

  # descrição do job
  e2e-tests:
    # máquina que o job vai executar
    runs-on: ['ubuntu-latest']

    # passo a passo das ações do job
    steps:
      # puxa o código para o repositório
      - uses: actions/checkout@v4

      # instalando o node
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # simular a execução de um comando no terminal
      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Testes E2E (end-to-end)
        run: yarn run test

        # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
