# CI de Nível 03 - Disparo automático sempre que outro for concluído, como deploy

# nome que vai aparecer nas opções de pipe
name: 'Execução por Deploy'

# regras oe disparo de execução (triggers/gatilhos)
  # gatilho de exec após outro workflow = workflow_run

on:
  workflow_run:
    workflows: ['Execução Manual'] # essa execução é a que está no arquivo 01
    types:
      - completed 


jobs:

  # descrição do job
  e2e-tests:

    # máquina que o job vai executar
    runs-on: 'ubuntu-latest'

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # passo a passo das ações do job
    steps:

      # puxa o código para o repositório
      - uses: actions/checkout@v4

      # instalando o node
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # simular a execução de um comando no terminal
      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Testes E2E (end-to-end)
        run: yarn run test

        # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report

      
