# CI de Nível 04 - Disparo dentro do fluxo de CI de desenvolvimento

# nome que vai aparecer nas opções de pipe
name: 'Execução Integrada'

# regras de disparo da execução (triggers/gatilhos)
  # gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:

jobs:

  inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Padronização de codigo (Lint)
        run: yarn lint

  unit:
    runs-on: ubuntu-latest
    needs: [inspection]

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Testes de Unidade
        run: yarn run test

  # descrição do job
  e2e-tests:

    # máquina que o job vai executar
    runs-on: ['ubuntu-latest']
    needs: [unit]

    # passo a passo das ações do job
    steps:

      # puxa o código para o repositório
      - uses: actions/checkout@v4

      # instalando o node
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # simular a execução de um comando no terminal
      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Subir aplicacao local
        run: yarn start & # assim o terminal não ficará travado em apenas 1 comando

      - name: Testes E2E (end-to-end)
        run: yarn run test
        env:
          URL: 'http://localhost:3000'

        # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report

      
